### ISSUE TITLE
line in source could not understand

### ISSUE THREAD

**Issue by gonejack** [elafarge/nodejs-golang-buffered-channel#1]
Any reason this line exists for?

https://github.com/elafarge/nodejs-golang-buffered-channel/blob/219db3a21bf8099915a6eddb297e2ab1fdf07508/src/lib/channel.ts#L78

**Comment by elafarge** [comment]
Absolutely not :) 
Thanks for reporting this. I actually do not maintain this repo, it's mostly an experiment. Feel free to re-use the code as you please if it's of any use to you though, it's not licensed at all :D
